[program:mlflow]
command=/opt/conda/bin/mlflow server --backend-store-uri sqlite:////./mlflow.db --default-artifact-root ./artifacts --host 0.0.0.0 --port 30001
directory=/jczhang02/mlflow
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/mlflow/mlflow.log
stderr_logfile=/var/log/mlflow/mlflow-error.log
environment=PATH="/opt/conda/bin:%(ENV_PATH)s"
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=10
directory_mode=0755
